### ISSUE TITLE
Release v.1.1.0 vs v1.1.0

### ISSUE THREAD

**Issue by bgloyer** [k9spud/appswipe#1]
This is nice.

But there is an extra dot in the version tag (v.1.1.0 vs v1.1.0).  I was trying to add this to the guru overlay but portage doesn't like the extra dot.

**Comment by k9spud** [comment]
I think I've got the release tags cleaned up now. Thanks for adding App Swipe!

**Comment by bgloyer** [comment]
FYI, It's in GURU now
